AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI-powered command parser for Google Sheets financial tracking

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: java17

Parameters:
  OpenAIApiKey:
    Type: String
    Description: OpenAI API Key
    NoEcho: true
  SheetsQueueUrl:
    Type: String
    Description: URL of the SQS queue for google-sheets-lambda
    Default: ""
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, prod]

Resources:
  # ============ LAMBDA ============
  AICommandParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub google-sheets-ai-parser-${Environment}
      Handler: com.github.dimka9910.sheets.ai.GoogleSheetsLambdaFunction::handleRequest
      CodeUri: .
      Description: Parses natural language commands using AI and sends to sheets-lambda
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
          SHEETS_QUEUE_URL: !Ref SheetsQueueUrl
          RESPONSE_QUEUE_URL: !Ref ResponseQueue
          USERS_TABLE_NAME: !Ref UsersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ResponseQueue.QueueName
        # Policy for sheets-queue (from another stack)
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:sheets-queue-*"
      Events:
        # POST /parse - парсинг команд
        ParseCommand:
          Type: Api
          Properties:
            Path: /parse
            Method: POST
        # GET /users/{userId} - получить контекст
        GetUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: GET
        # PUT /users/{userId} - создать/обновить контекст
        PutUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: PUT
        # PATCH /users/{userId}/defaults - обновить дефолты
        PatchDefaults:
          Type: Api
          Properties:
            Path: /users/{userId}/defaults
            Method: PATCH
        # PATCH /users/{userId}/telegram - привязать Telegram
        PatchTelegram:
          Type: Api
          Properties:
            Path: /users/{userId}/telegram
            Method: PATCH
        # POST /users/{userId}/instructions - добавить инструкцию
        AddInstruction:
          Type: Api
          Properties:
            Path: /users/{userId}/instructions
            Method: POST
        # DELETE /users/{userId}/instructions/{index} - удалить инструкцию
        DeleteInstruction:
          Type: Api
          Properties:
            Path: /users/{userId}/instructions/{index}
            Method: DELETE
        # POST /users/{userId}/accounts - добавить счёт
        AddAccount:
          Type: Api
          Properties:
            Path: /users/{userId}/accounts
            Method: POST
        # POST /users/{userId}/funds - добавить фонд
        AddFund:
          Type: Api
          Properties:
            Path: /users/{userId}/funds
            Method: POST

  # ============ DYNAMODB ============
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub finance-tracker-users-${Environment}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: telegramId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: telegramId-index
          KeySchema:
            - AttributeName: telegramId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: finance-tracker

  # ============ SQS ============
  ResponseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub telegram-responses-${Environment}
      VisibilityTimeout: 30

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  
  UsersTableName:
    Description: DynamoDB table for user contexts
    Value: !Ref UsersTable
  
  UsersTableArn:
    Description: ARN of DynamoDB table
    Value: !GetAtt UsersTable.Arn
  
  ResponseQueueUrl:
    Description: URL of SQS queue for Telegram responses
    Value: !Ref ResponseQueue
