package com.github.dimka9910.sheets.ai.services;

import com.github.dimka9910.sheets.ai.db.service.FinancialOperationService;
import com.github.dimka9910.sheets.ai.dto.response.*;
import com.github.dimka9910.sheets.ai.dto.telegram.TelegramChatRequest;
import com.github.dimka9910.sheets.ai.dto.telegram.TelegramChatResponse;
import com.github.dimka9910.sheets.ai.dto.user.ConversationMessage;
import com.github.dimka9910.sheets.ai.dto.user.UserEntity;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Spring Service for handling MainAgentResponse results.
 * 
 * Responsibilities:
 * - Execute settings actions (add account, undo, etc.)
 * - Save financial actions to PostgreSQL database
 * - Manage pending clarifications in UserEntity
 * - Build TelegramChatResponse with model's response message
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class MainAgentResultHandler {

    @SuppressWarnings("unused")
    private final SQSPublisher sqsPublisher;
    private final UserEntityService userContextService;
    @SuppressWarnings("unused")
    private final CustomInstructionHandler customInstructionHandler;
    private final Optional<FinancialOperationService> financialOperationService;
    
    @PostConstruct
    public void init() {
        if (financialOperationService.isPresent()) {
            log.info("✅ ResultHandler initialized with DATABASE support");
        } else {
            log.warn("⚠️ ResultHandler initialized WITHOUT database support (DATABASE_URL not set)");
        }
    }

    /**
     * Process agent response and return TelegramChatResponse.
     * 
     * Handles different response types:
     * - FinancialAgentResponse: save financial operations
     * - CustomInstructionAgentResponse: update user settings
     * - MainAgentResponse: pure conversational (no actions)
     * 
     * NOTE: CUSTOM_INSTRUCTION actions are processed asynchronously.
     * If CustomInstructionAgent needs clarification, it will send a SECOND message to user.
     */
    public TelegramChatResponse handle(TelegramChatRequest request, BaseAgentResponse agentResponse, UserEntity userContext) {
        String chatId = request.getResponseChatId();
        String message = request.getMessage();
        
        // Add user message to history
        userContext.addToHistory(ConversationMessage.userMessage(message));
        
        // Extract actions based on response type
        List<FinancialAction> financialActions = new ArrayList<>();
        List<CustomInstructionAction> customInstructionActions = new ArrayList<>();
        List<PendingClarificationAction> pendingActions = agentResponse.getPendingClarifications() != null 
                ? agentResponse.getPendingClarifications() 
                : new ArrayList<>();
        
        if (agentResponse instanceof FinancialAgentResponse financialResponse) {
            financialActions = financialResponse.getFinancialActions() != null 
                    ? financialResponse.getFinancialActions() 
                    : new ArrayList<>();
            log.info("Processing FinancialAgentResponse: {} financial actions, {} pending", 
                    financialActions.size(), pendingActions.size());
        } else if (agentResponse instanceof CustomInstructionAgentResponse instructionResponse) {
            customInstructionActions = instructionResponse.getCustomInstructionActions() != null
                    ? instructionResponse.getCustomInstructionActions()
                    : new ArrayList<>();
            log.info("Processing CustomInstructionAgentResponse: {} instruction actions, {} pending", 
                    customInstructionActions.size(), pendingActions.size());
        } else {
            // MainAgentResponse - pure conversational, no actions
            log.info("Processing MainAgentResponse: conversational only, {} pending", pendingActions.size());
        }
        
        // Handle pending clarifications
        if (!pendingActions.isEmpty()) {
            userContext.setPendingActions(pendingActions);
            log.info("Saved {} pending clarifications", pendingActions.size());
        } else {
            userContext.clearPendingActions();
        }
        
        // Handle instruction actions (settings updates)
        if (!customInstructionActions.isEmpty()) {
            handleInstructionActions(customInstructionActions, userContext);
        }
        
        // Handle financial actions
        boolean allSuccess = true;
        int operationsCount = 0;
        List<FinancialAction> successfulActions = new ArrayList<>();
        
        for (FinancialAction action : financialActions) {
            // Note: UUID will be generated by database (@GeneratedValue) and set after save
            
            boolean success = handleFinancialAction(action, userContext);
            if (success) {
                operationsCount++;
                successfulActions.add(action);
            } else {
                allSuccess = false;
            }
        }
        
        // Determine success
        boolean hasFinancialWork = !financialActions.isEmpty();
        boolean isSuccess = hasFinancialWork ? allSuccess && operationsCount > 0 : true;

        
        // Add assistant response to history with related financial actions
        log.debug("💾 Adding to history: {} successful actions", successfulActions.size());
        if (!successfulActions.isEmpty()) {
            for (var action : successfulActions) {
                log.debug("  💾 Action: ID={}, Type={}, Amount={}", 
                    action.getId(), action.getOperationType(), action.getAmount());
            }
        }
        
        userContext.addToHistory(ConversationMessage.builder()
                .role("assistant")
                .content(agentResponse.getMessage())
                .relatedFinancialActions(successfulActions)
                .build());
        
        // Save ONLY conversation history + AI context (NOT accounts/funds to avoid constraint violations)
        userContextService.saveConversationAndAiContext(userContext);
        
        return TelegramChatResponse.builder()
                .chatId(chatId)
                .success(isSuccess)
                .message(agentResponse.getMessage())
                .operationsCount(operationsCount)
                .build();
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // INSTRUCTION ACTIONS (Settings/Aliases/Defaults)
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Handle instruction actions from CustomInstructionAgent.
     * These actions modify user settings: aliases, defaults, custom instructions.
     */
    private void handleInstructionActions(List<CustomInstructionAction> actions, UserEntity userContext) {
        log.info("Processing {} instruction actions", actions.size());
        
        for (CustomInstructionAction action : actions) {
            handleInstructionAction(action, userContext);
        }
    }
    
    /**
     * Handle single InstructionAction.
     */
    private void handleInstructionAction(CustomInstructionAction action, UserEntity userContext) {
        log.info("Instruction action: {} (entity={}, entityId={}, value={})", 
                action.getActionType(), action.getEntityType(), action.getEntityId(), action.getValue());
        
        try {
            switch (action.getActionType()) {
                case UPDATE_DEFAULT -> handleUpdateDefault(action, userContext);
                case ADD_LINKED_USER_ALIAS -> handleAddLinkedUserAlias(action, userContext);
                case REMOVE_LINKED_USER_ALIAS -> handleRemoveLinkedUserAlias(action, userContext);
                case ADD_ACCOUNT_ALIAS -> handleAddAccountAlias(action, userContext);
                case REMOVE_ACCOUNT_ALIAS -> handleRemoveAccountAlias(action, userContext);
                case ADD_FUND_ALIAS -> handleAddFundAlias(action, userContext);
                case REMOVE_FUND_ALIAS -> handleRemoveFundAlias(action, userContext);
                case ADD_CUSTOM_INSTRUCTION -> handleAddCustomInstruction(action, userContext);
                case REMOVE_CUSTOM_INSTRUCTION -> handleRemoveCustomInstruction(action, userContext);
                default -> log.warn("⚠️ Unknown instruction action type: {}", action.getActionType());
            }
        } catch (Exception e) {
            log.error("❌ Error handling instruction action {}: {}", action.getActionType(), e.getMessage(), e);
        }
    }
    
    private void handleUpdateDefault(CustomInstructionAction action, UserEntity userContext) {
        String entityId = action.getEntityId(); // e.g., "currency", "account", "fund", "language"
        String value = action.getValue();
        
        switch (entityId.toLowerCase()) {
            case "currency", "defaultcurrency" -> {
                userContext.setDefaultCurrency(value);
                log.info("✅ Updated default currency to: {}", value);
            }
            case "language", "preferredlanguage" -> {
                userContext.setPreferredLanguage(value);
                log.info("✅ Updated preferred language to: {}", value);
            }
            default -> log.warn("⚠️ Unknown default entity: {}", entityId);
        }
    }
    
    private void handleAddLinkedUserAlias(CustomInstructionAction action, UserEntity userContext) {
        String targetUserName = action.getEntityId(); // e.g., "KIKI"
        String alias = action.getValue(); // e.g., "girlfriend"
        
        if (targetUserName == null || alias == null) {
            log.warn("⚠️ ADD_LINKED_USER_ALIAS: missing entityId or value");
            return;
        }
        
        // Update in memory (for current request)
        var linkedUser = userContext.getLinkedUsers().stream()
            .filter(lu -> lu.getUserName().equals(targetUserName))
            .findFirst();
        
        if (linkedUser.isPresent()) {
            if (!linkedUser.get().getAliases().contains(alias)) {
                linkedUser.get().getAliases().add(alias);
            }
        }
        
        // Save to database
        userContextService.addLinkedUserAlias(userContext.getId(), targetUserName, alias);
    }
    
    private void handleRemoveLinkedUserAlias(CustomInstructionAction action, UserEntity userContext) {
        String targetUserName = action.getEntityId(); // e.g., "KIKI"
        String alias = action.getValue(); // e.g., "girlfriend"
        
        if (targetUserName == null || alias == null) {
            log.warn("⚠️ REMOVE_LINKED_USER_ALIAS: missing entityId or value");
            return;
        }
        
        // Update in memory
        var linkedUser = userContext.getLinkedUsers().stream()
            .filter(lu -> lu.getUserName().equals(targetUserName))
            .findFirst();
        
        if (linkedUser.isPresent()) {
            linkedUser.get().getAliases().remove(alias);
        }
        
        // Save to database
        userContextService.removeLinkedUserAlias(userContext.getId(), targetUserName, alias);
    }
    
    private void handleAddAccountAlias(CustomInstructionAction action, UserEntity userContext) {
        String accountId = action.getEntityId(); // e.g., "CARD_DIMA_VISA_RAIF"
        String alias = action.getValue(); // e.g., "raif"
        
        if (accountId == null || alias == null) {
            log.warn("⚠️ ADD_ACCOUNT_ALIAS: missing entityId or value");
            return;
        }
        
        // Update in memory
        var account = userContext.getAccounts().stream()
            .filter(acc -> acc.getAccountId().equals(accountId))
            .findFirst();
        
        if (account.isPresent()) {
            if (!account.get().getAliases().contains(alias)) {
                account.get().getAliases().add(alias);
            }
        }
        
        // Save to database
        userContextService.addAccountAlias(userContext.getId(), accountId, alias);
    }
    
    private void handleRemoveAccountAlias(CustomInstructionAction action, UserEntity userContext) {
        String accountId = action.getEntityId(); // e.g., "CARD_DIMA_VISA_RAIF"
        String alias = action.getValue(); // e.g., "raif"
        
        if (accountId == null || alias == null) {
            log.warn("⚠️ REMOVE_ACCOUNT_ALIAS: missing entityId or value");
            return;
        }
        
        // Update in memory
        var account = userContext.getAccounts().stream()
            .filter(acc -> acc.getAccountId().equals(accountId))
            .findFirst();
        
        if (account.isPresent()) {
            account.get().getAliases().remove(alias);
        }
        
        // Save to database
        userContextService.removeAccountAlias(userContext.getId(), accountId, alias);
    }
    
    private void handleAddFundAlias(CustomInstructionAction action, UserEntity userContext) {
        String fundId = action.getEntityId(); // e.g., "FOOD"
        String alias = action.getValue(); // e.g., "cafe"
        
        if (fundId == null || alias == null) {
            log.warn("⚠️ ADD_FUND_ALIAS: missing entityId or value");
            return;
        }
        
        // Update in memory
        var fund = userContext.getFunds().stream()
            .filter(f -> f.getFundId().equals(fundId))
            .findFirst();
        
        if (fund.isPresent()) {
            if (!fund.get().getAliases().contains(alias)) {
                fund.get().getAliases().add(alias);
            }
        }
        
        // Save to database
        userContextService.addFundAlias(userContext.getId(), fundId, alias);
    }
    
    private void handleRemoveFundAlias(CustomInstructionAction action, UserEntity userContext) {
        String fundId = action.getEntityId(); // e.g., "FOOD"
        String alias = action.getValue(); // e.g., "cafe"
        
        if (fundId == null || alias == null) {
            log.warn("⚠️ REMOVE_FUND_ALIAS: missing entityId or value");
            return;
        }
        
        // Update in memory
        var fund = userContext.getFunds().stream()
            .filter(f -> f.getFundId().equals(fundId))
            .findFirst();
        
        if (fund.isPresent()) {
            fund.get().getAliases().remove(alias);
        }
        
        // Save to database
        userContextService.removeFundAlias(userContext.getId(), fundId, alias);
    }
    
    private void handleAddCustomInstruction(CustomInstructionAction action, UserEntity userContext) {
        String instruction = action.getValue(); // e.g., "называй меня своим папиком"
        
        if (instruction == null || instruction.isBlank()) {
            log.warn("⚠️ ADD_CUSTOM_INSTRUCTION: missing value");
            return;
        }
        
        // Add to user context (will be saved by saveConversationAndAiContext)
        userContext.addInstruction(instruction);
        log.info("✅ Added custom instruction: '{}'", instruction);
    }
    
    private void handleRemoveCustomInstruction(CustomInstructionAction action, UserEntity userContext) {
        Integer index = action.getIndex();
        String value = action.getValue();
        
        // Support removal by index OR by value
        if (index != null) {
            userContext.removeInstruction(index);
            log.info("✅ Removed custom instruction at index {}", index);
        } else if (value != null) {
            // Remove by matching value
            List<String> instructions = userContext.getCustomInstructions();
            if (instructions != null) {
                boolean removed = instructions.remove(value);
                if (removed) {
                    log.info("✅ Removed custom instruction: '{}'", value);
                } else {
                    log.warn("⚠️ Custom instruction not found: '{}'", value);
                }
            }
        } else {
            log.warn("⚠️ REMOVE_CUSTOM_INSTRUCTION: missing both index and value");
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // FINANCIAL ACTIONS
    // ═══════════════════════════════════════════════════════════════════════════

    private boolean handleFinancialAction(FinancialAction action, UserEntity userContext) {
        if (action.getOperationType() == null) {
            log.warn("❌ Financial action missing operationType: {}", action);
            return false;
        }
        
        // Check if database is available
        if (financialOperationService.isEmpty()) {
            log.error("❌ DATABASE_URL not configured, cannot save financial operation");
            return false;
        }

        // Corrections: MODIFY/DELETE
        if (action.getOperationType() == FinancialAction.OperationType.MODIFY) {
            if (action.getId() == null) {
                log.warn("❌ MODIFY missing id: {}", action);
                return false;
            }
            try {
                financialOperationService.get().modifyOperation(action.getId(), action, userContext);
                log.info("✅ MODIFY applied: id={}", action.getId());
                return true;
            } catch (Exception e) {
                log.error("❌ Failed to MODIFY operation {}", action.getId(), e);
                return false;
            }
        }

        if (action.getOperationType() == FinancialAction.OperationType.DELETE) {
            if (action.getId() == null) {
                log.warn("❌ DELETE missing id: {}", action);
                return false;
            }
            try {
                financialOperationService.get().deleteOperation(action.getId());
                log.info("✅ DELETE applied: id={}", action.getId());
                return true;
            } catch (Exception e) {
                log.error("❌ Failed to DELETE operation {}", action.getId(), e);
                return false;
            }
        }

        // Validate required fields for NEW operations
        if (action.getAmount() == null || action.getAmount() <= 0) {
            log.warn("❌ Financial action missing amount: {}", action);
            return false;
        }
        
        try {
            // Save to database based on operation type
            // Database will generate UUID via @GeneratedValue
            switch (action.getOperationType()) {
                case EXPENSE -> {
                    var saved = financialOperationService.get().saveExpense(action, userContext);
                    action.setId(saved.getId()); // Update action with DB-generated UUID
                    log.info("✅ EXPENSE saved to database: {} {} {}", 
                        action.getAmount(), action.getCurrency(), action.getAccount());
                }
                case INCOME -> {
                    var saved = financialOperationService.get().saveIncome(action, userContext);
                    action.setId(saved.getId()); // Update action with DB-generated UUID
                    log.info("✅ INCOME saved to database: {} {} {}", 
                        action.getAmount(), action.getCurrency(), action.getAccount());
                }
                case TRANSFER -> {
                    var saved = financialOperationService.get().saveTransfer(action, userContext);
                    // For transfers, use the first (debit) record's ID
                    action.setId(saved.get(0).getId());
                    log.info("✅ TRANSFER saved to database: {} {} {} → {}", 
                        action.getAmount(), action.getCurrency(), action.getAccount(), action.getTargetAccount());
                }
                default -> {
                    log.warn("❌ Unknown operation type: {}", action.getOperationType());
                    return false;
                }
            }
            
            return true;
            
        } catch (Exception e) {
            log.error("❌ Failed to save financial operation to database", e);
            return false;
        }
    }

}
